"use strict";
//Assighnment operator
var _a;
let n = 5;
console.log(n);
n += 5;
console.log(n);
n -= 5;
console.log(n);
let i = 6;
console.log(i);
i += 50;
console.log(i);
i -= 80;
console.log(i);
let y = 60;
console.log(y);
y /= 6;
console.log(y);
y *= 5;
console.log(y);
y -= 10;
console.log(y);
y %= 6;
console.log(y);
y **= 8;
console.log(y);
let strg = "Hello";
console.log(strg.split(""));
let stir = "5" + 2;
console.log(stir);
let str = "Hello, World!";
console.log(str.slice(0, 5));
let ser = "Hello, World!";
console.log(ser.substr(-3));
let num = 8;
let multiplier = 2;
num *= multiplier += 3;
console.log(num);
let e = "Hello";
let c = "hello";
let result = e < c;
console.log(result);
let x = true;
let p = 5;
let resulp = x && (y > 10);
console.log(resulp);
let namer = "hamid";
let falbacknamer = "anonymous";
let resultp = (_a = namer !== null && namer !== void 0 ? namer : falbacknamer) !== null && _a !== void 0 ? _a : "Guest";
console.log(resultp);
let o = undefined;
let u;
let resulto = o === u;
console.log(resulto);
